name: Playwright
description: Performs playwright tests checks
inputs:
  working-directory:
    description: "Relative path to app"
    default: "."
  project:
    description: "Playwright project to use"
    required: true
    default: "chromium"
  api-key:
    required: true
    description: "Replay.io API Key"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "17"
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: ${{ inputs.working-directory }}
    - uses: replayio/action-playwright@main
      with:
        project: ${{ inputs.project }}
        api-key: ${{ inputs.api-key }}
        working-directory: ${{ inputs.working-directory }}
