name: Playwright
description: Performs playwright tests checks
inputs:
  working-directory:
    description: "Relative path to app"
    default: "."
  project:
    description: "Playwright project to use"
    required: true
    default: "chromium"
  api-key:
    required: true
    description: "Replay.io API Key"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "18"
        cache: "yarn"
    - uses: replayio/action-playwright@main
      with:
        project: ${{ inputs.project }}
        api-key: ${{ inputs.api-key }}
        working-directory: ${{ inputs.working-directory }}
    - run: node test/upload-and-check-recording.js
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        REPLAY_API_KEY: ${{ inputs.api-key }}
