name: Build, lint and test

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: replayio-public/flake
          path: e2e-repos/flake
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.19/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: build, lint and test
        run: |
          cp $GITHUB_EVENT_PATH ./e2e-repos/flake/github_event
          earthly +ci \
            --REPLAY_API_KEY="${{ secrets.CYPRESS_API_KEY }}" \
            --GITHUB_SHA="$GITHUB_SHA" \
            --GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            --GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            --GITHUB_ACTOR="$GITHUB_ACTOR" \
            --GITHUB_RUN_ID="$GITHUB_RUN_ID" \
            --GITHUB_WORKFLOW="$GITHUB_WORKFLOW" \
            --GITHUB_REF_NAME="$GITHUB_REF_NAME" \
            --GITHUB_SERVER_URL="$GITHUB_SERVER_URL"
