name: Check Install

on: [pull_request, workflow_dispatch]

env:
  DEBUG: replay:*

jobs:
  install:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run bootstrap
      - run: npm link ./packages/cypress/dist

      - name: Cypress Install
        run: npx @replayio/cypress install
      - name: List Installed Browsers
        run: node ./.github/scripts/install.js
