name: Create React App Typescript Tests
on:
  pull_request:

jobs:
  playwright-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn --immutable
        shell: bash
        working-directory: .
      - run: yarn run bootstrap
        shell: bash
        working-directory: .
      - uses: ./.github/actions/playwright
        with:
          project: "replay-chromium"
          api-key: ${{ secrets.REPLAY_API_KEY || secrets.RECORD_REPLAY_API_KEY }}
          working-directory: examples/create-react-app-typescript
