name: Playwright tests
on:
  pull_request:
  push:
    branches: main, playwright-next

jobs:
  playwright-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        playwright-version: [1.30.x, 1.44.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn --immutable
      # @playwright/test depends on fixed version of playwright and that depends on fixed version of playwright-core
      # so it should be enough to only enforce the version of @playwright/test here
      - run: yarn set resolution @playwright/test@${{ matrix.playwright-version }}
      - run: yarn run bootstrap
      - run: cd examples/create-react-app-typescript
      - run: yarn test
      - run: node test/upload-and-check-recording.js
        working-directory: examples/create-react-app-typescript
        env:
          REPLAY_API_KEY: ${{ secrets.RECORD_REPLAY_API_KEY }}
